% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{section}{-1}
\usepackage{fvextra}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{
  showspaces = false,
  showtabs = false,
  breaklines,
  commandchars=\\\{\}

\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={QRM II Graded Assignment 2},
  pdfauthor={Group 17: Omar Zakkouralashy, Anna Olaru, Nando Fredricks, Floris Hemink},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{QRM II Graded Assignment 2}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Period 1, 2026}
\author{Group 17: Omar Zakkouralashy, Anna Olaru, Nando Fredricks,
Floris Hemink}
\date{27-09-2026}

\begin{document}
\maketitle

\section{Introduction}\label{introduction}

This assignment is to be completed in groups of 4-5. Further, all
students in your group need to be assigned to the same R tutorial group
(Friday's tutorial). You can sign yourself up for a group on Canvas.
Please do so
\textbf{before the start of your first R tutorial on Friday September 4th.}
You can use the Discussion Board in Canvas if you do not have a group
yet or if your group is incomplete.

The assignment has 5 parts, and each part corresponds to the course
material of that week (with the exclusion of week 6, for which there is
no R programming material).

You are supposed to hand in these assignments on Canvas at the following
dates:

\begin{itemize}
\tightlist
\item
  \textbf{Deadline 1} \emph{Sunday September 27th, at 23:59pm}: you are
  supposed to hand in weeks 1, 2, and 3 of this assignment. This will
  determine 18\% of your overall course grade
\item
  \textbf{Deadline 2} \emph{Sunday October 11th, at 23:59pm}: you are
  supposed to hand in weeks 4, and 5 of this assignment. This will
  determine 12\% of your overall course grade
\end{itemize}

The R tutorials (each Friday) will consist of two halves. During the
first half, you will discuss the tutorial exercises. These can be
downloaded separately from Canvas. During the second half, you can work
on this graded assignment within your own group. The purpose is that you
find out how to work with R for doing statistical analyses by yourself.
The tutorial exercises are meant to teach you basic commands to get you
started, but to answer the problem sets in this assignment, you might
need to research your own solutions, and use functions and commands not
described in the tutorial exercises. Learning how to solve your own
research problems is integral part of learning R. When you and your
group get stuck on how to approach an exercise, the hierarchy in finding
your way is as follows:

\begin{itemize}
\tightlist
\item
  use the concepts from the tutorial exercises;
\item
  use the cheat sheets available on Canvas;
\item
  use Google, YouTube, StackOverflow, or another website;
\item
  ask the teacher.
\end{itemize}

The use of generative AI is \textbf{not} permitted and may result in a
grade of 0. See the AI protocol in the course manual for details.

To answer the assignment, you can simply fill out this R markdown
document. There are designated places which you can fill with R code.
There are also designated spaces for you to answer each question. Often,
the structure of an answer will be as follows. First, you type the R
code in the designated box. This will show how you analyzed the data to
get the answer to the question. Below the box for the R code, you will
then summarize your answer to the question, i.e.~what are the
conclusions that you draw from the data analysis?

When handing in, you are supposed to submit this .Rmd file, and a
knitted version of this document. You can knit this document to pdf,
word, or html. Knitting to pdf requires you to have a .tex distribution
installed on your computer. Knitting to Word requires you to have Word
installed.

The exercises are designed such that you should be able to finish the
majority of them during the tutorial each week. If you are not able to
finish them fully during that time, you are expected to work on it in
your own time using the computers on campus or your own device. It is
best to meet as a group in-person when working together. If you want to
work remotely, github is a good platform to guarantee smooth
collaboration. Alternatively, you can email this .Rmd file back and
forth to one another as a group, but this is not recommended as it is
more cumbersome.

We encourage you to keep your code blocks, printing statements, and
final answers, as short as possible. In any case, there is a page limit
of 6 pages per week, which encompasses the total length of this document
which consists of the questions, your coding lines, and your answers.
When your answers to questions of the respective week exceed this page
limit, they will not be graded, resulting in zero points.

Each week consists of 1, 2, or 3 subquestions. The total amount of
points you can earn per week is 20 points.

\section{Week 1}\label{week-1}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Find the dataset ``movies5.tsv'' on Canvas. Describe your data set:
  How many observations does it have. How many variables are there? How
  many subjects? What consists of a subject? \textbf{[4 points]}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies5}\OtherTok{\textless{}{-}}\FunctionTok{read.table}\NormalTok{(}\StringTok{"movies5.tsv"}\NormalTok{,}\AttributeTok{sep=}\StringTok{"}\SpecialCharTok{\textbackslash{}t}\StringTok{"}\NormalTok{, }\AttributeTok{header=}\ConstantTok{TRUE}\NormalTok{ )}
\FunctionTok{dim}\NormalTok{(movies5)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 909  19
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{nrow}\NormalTok{(movies5)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 909
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ncol}\NormalTok{(movies5)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 19
\end{verbatim}

\textbf{Your Answer:}

The dataset has 909 observations and 19 variables. Each observation is
one movie so a subject is one movie.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Which of the following types of variables are present in your data
  set? (i) nominal; (ii) ordinal; (iii); interval; (iv) ratio. If
  present, name one example of such a variable present in your data set.
  \textbf{[4 points]}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(movies5)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      index          budget               keywords   original_language
##  Min.   :   3   Min.   :        0   Length   :909   Length   :909    
##  1st Qu.:1048   1st Qu.:  1500000   N.unique :799   N.unique : 19    
##  Median :2195   Median : 18000000   N.blank  :  0   N.blank  :  0    
##  Mean   :2263   Mean   : 32561665   Min.nchar:  2   Min.nchar:  2    
##  3rd Qu.:3362   3rd Qu.: 45000000   Max.nchar:103   Max.nchar:  2    
##  Max.   :4802   Max.   :250000000   NAs      : 89                    
##        title       popularity           release_date    revenue         
##  Length   :909   Min.   :  0.00239   Length   :909   Min.   :0.000e+00  
##  N.unique :909   1st Qu.:  5.02309   N.unique :810   1st Qu.:0.000e+00  
##  N.blank  :  0   Median : 14.03851   N.blank  :  0   Median :2.548e+07  
##  Min.nchar:  1   Mean   : 22.93180   Min.nchar: 10   Mean   :8.885e+07  
##  Max.nchar: 66   3rd Qu.: 29.60832   Max.nchar: 10   3rd Qu.:1.016e+08  
##                  Max.   :875.58130                   Max.   :1.157e+09  
##     runtime     vote_average     vote_count            genre      release_year 
##  Min.   :  0   Min.   :0.000   Min.   :    0.0   Length   :909   Min.   :1990  
##  1st Qu.: 95   1st Qu.:5.500   1st Qu.:   61.0   N.unique : 14   1st Qu.:2001  
##  Median :105   Median :6.200   Median :  251.0   N.blank  :  0   Median :2006  
##  Mean   :107   Mean   :6.011   Mean   :  744.6   Min.nchar:  5   Mean   :2006  
##  3rd Qu.:118   3rd Qu.:6.800   3rd Qu.:  799.0   Max.nchar: 11   3rd Qu.:2011  
##  Max.   :214   Max.   :9.500   Max.   :10099.0   NAs      :  7   Max.   :2016  
##  release_month     release_day       first_actor  first_actor_gender
##  Min.   : 1.000   Min.   : 1.00   Length   :909   Length   :909     
##  1st Qu.: 4.000   1st Qu.: 8.00   N.unique :609   N.unique :  2     
##  Median : 8.000   Median :16.00   N.blank  :  0   N.blank  :  0     
##  Mean   : 6.942   Mean   :15.53   Min.nchar:  6   Min.nchar:  4     
##  3rd Qu.:10.000   3rd Qu.:23.00   Max.nchar: 23   Max.nchar:  6     
##  Max.   :12.000   Max.   :31.00   NAs      :  6   NAs      : 37     
##  director_first_name  director_gender
##  Length   :909       Length   :909   
##  N.unique :387       N.unique :  2   
##  N.blank  :  0       N.blank  :  0   
##  Min.nchar:  2       Min.nchar:  4   
##  Max.nchar: 12       Max.nchar:  6   
##  NAs      :  3       NAs      : 47
\end{verbatim}

\textbf{Your Answer:}

The dataset has nominal (genre), interval (vote\_average), and ratio
(budget, revenue, runtime) variables. No variables fit the ordinal
description.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  A movie studio wants to know which types of movies give maximal
  profit. Perform the following steps to provide the movie studio with
  an analysis which corresponds to their request:
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create the variable profits as the revenue of a movie minus its
  budget. Report its mean, median, maximum, and minimum.
  \textbf{[2 points]}
\item
  Which movie has the highest profits in your data set and how much are
  these profits. Which movie has the lowest and how much are its
  profits? If multiple movies have the exact same highest or lowest
  profits, give only one example. \textbf{[2 points]}
\item
  Create a boxplot of the variable profits. Make sure it has an
  appropriate title, and appropriate titles and labels for the x- and
  y-axis. Give Q1, Q2, Q3, and Q4. What does this tell you about the
  nature of making money in the movies industry? \textbf{[2 points]}
\item
  Add a new variable to your data set the log of profits. When creating
  this variable, what happens to movies for which profits is zero or
  negative? What then happens when you calculate the mean of log of
  profits? \textbf{[2 points]}
\item
  For movies that have a profit of zero or less, replace log of profits
  with ``NA''. What is now the mean of log of profits? Create a boxplot
  for log of profits, again with an appropriate title, x- and y-axis
  labels. How does it compare to the boxplot you made under c.)?
  \textbf{[2 points]}
\item
  Create a scatterplot of with the runtime of movies on the x-axis and
  the average vote of movies on the y-axis. What do you conclude from
  the scatterplot? Are movies with a longer runtime considered worse or
  better by the audience, or does the audience not have a preference?
  Why do you think this is the case? \textbf{[2 points]}
\end{enumerate}

For each step, you should provide first all the code you used to answer
the question and then formulate an answer using full sentences.

\emph{Step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies5}\SpecialCharTok{$}\NormalTok{profits }\OtherTok{\textless{}{-}}\NormalTok{ movies5}\SpecialCharTok{$}\NormalTok{revenue }\SpecialCharTok{{-}}\NormalTok{ movies5}\SpecialCharTok{$}\NormalTok{budget}
\FunctionTok{mean}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{profits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 56284650
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{median}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{profits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2942221
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{max}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{profits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1082730962
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{min}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{profits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -98301101
\end{verbatim}

\textbf{Your Answer:}

The mean profit is 56,284,650, the median is 2,942,221, the max is
1,082,730,962, and the min is -98,301,101.

\emph{Step b}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies5[}\FunctionTok{which.max}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{profits), }\FunctionTok{c}\NormalTok{(}\StringTok{"title"}\NormalTok{, }\StringTok{"profits"}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       title    profits
## 870 Minions 1082730962
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies5[}\FunctionTok{which.min}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{profits), }\FunctionTok{c}\NormalTok{(}\StringTok{"title"}\NormalTok{, }\StringTok{"profits"}
\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                title   profits
## 854 The 13th Warrior -98301101
\end{verbatim}

\textbf{Your Answer:}

The most profitable movie is Minions, with profits of 1,082,730,962. The
least profitable is The 13th Warrior, with a loss of 98,301,101.

\emph{Step c}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{profits,}
        \AttributeTok{main=} \StringTok{"Boxplot of movie profits"}\NormalTok{,}
        \AttributeTok{xlab=} \StringTok{"movies5"}\NormalTok{,}
        \AttributeTok{ylab=} \StringTok{"Profits"}\NormalTok{,}
        \AttributeTok{col=} \StringTok{"lightblue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment-2-Submission-1_files/Assignment-2-Submission-1_files/figure-latex/unnamed-chunk-5-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{quantile}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{profits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         0%        25%        50%        75%       100% 
##  -98301101   -1260859    2942221   61340801 1082730962
\end{verbatim}

\textbf{Your Answer:}

From these quartiles we can see that the movie industry is a very risky
and hit driven industry because the first quartile is negative, showing
losses. Meanwhile the shift from second to third quartile suggests that
the majority of revenue in the industry is generated by a small number
of movies. Q1 = -1,260,859 Q2 = 2,942,221 Q3 = 61,340,801 Q4 =
1,082,730,962

\emph{Step d}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies5}\SpecialCharTok{$}\NormalTok{logprofits }\OtherTok{\textless{}{-}} \FunctionTok{log}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{profits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in log(movies5$profits): NaNs produced
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{logprofits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] NaN
\end{verbatim}

\textbf{Your Answer:}

The mean of logprofits is NaN because the dataset contains zero and
negative profits. The logarithm of zero results in -Inf, while the
logarithm of a negative value results in NaN.

\emph{Step e}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies5}\SpecialCharTok{$}\NormalTok{logprofits[movies5}\SpecialCharTok{$}\NormalTok{profits }\SpecialCharTok{\textless{}=} \DecValTok{0}\NormalTok{] }\OtherTok{\textless{}{-}} \ConstantTok{NA}

\FunctionTok{mean}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{logprofits, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 17.5448
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{logprofits,}
        
        \AttributeTok{main =} \StringTok{"Boxplot of Log Movie Profits"}\NormalTok{,}
        
        \AttributeTok{xlab =} \StringTok{"Movies"}\NormalTok{,}
        
        \AttributeTok{ylab =} \StringTok{"Log of Profits"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment-2-Submission-1_files/Assignment-2-Submission-1_files/figure-latex/unnamed-chunk-7-1.pdf}}

\textbf{Your Answer:}

We replace zero and negative profits with NA so they are excluded from
the calculation. The log transformation also reduces the influence of
extremely high profits, resulting in a more balanced distribution. The
mean of log profits is now 17.54.

\emph{Step f}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'ggplot2' was built under R version 4.6.1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(movies5, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ runtime, }\AttributeTok{y =}\NormalTok{ vote\_average)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{x =} \StringTok{"Runtime (minutes)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Average vote"}\NormalTok{,}
    \AttributeTok{title =} \StringTok{"Runtime vs Average Movie Vote"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment-2-Submission-1_files/Assignment-2-Submission-1_files/figure-latex/unnamed-chunk-8-1.pdf}}

\textbf{Your Answer}

The scatterplot shows a weak positive relationship between running time
and average vote, so longer movies get better ratings. The points are
very spread out, so the audience doesnt have a strong preference. Likely
because people rate a movie more on the story and genre than just
duration.

\section{Week 2}\label{week-2}

1 Is your dataset movies5.tsv the full population, or is it a sample of
a larger population? If the latter, how would you describe the full
population? \textbf{[4 points]}

\textbf{Your Answer:}

This is a sample of a larger population. The population would be all
movies from 1990 to 2016 in the mentioned 19 languages. Here we only
have a selection of movies and their ratings that should reflect the
population.

2

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  For which actor in your data set do you observe the most movies?
  \textbf{[2 points]}
\item
  What is the average revenue of the movie in which this actor plays and
  does the revenue lie above or below the revenue of an average movie
  according to your data set? \textbf{[2 points]}\\
\item
  How trustworthy do you consider your conclusion to answer 2b? Use the
  term ``law of large numbers'' in your explanation. \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(}\FunctionTok{sort}\NormalTok{(}\FunctionTok{table}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{first\_actor), }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{))[}\DecValTok{1}\NormalTok{] }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Bruce Willis"
\end{verbatim}

\textbf{Your Answer:}

Bruce Willis is the most frequently appearing actor in the movie list.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{revenue)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 88846315
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bruce\_movies }\OtherTok{\textless{}{-}}\NormalTok{ movies5[}\FunctionTok{which}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{first\_actor }\SpecialCharTok{==} \StringTok{"Bruce Willis"}\NormalTok{), ]}
\FunctionTok{mean}\NormalTok{(bruce\_movies}\SpecialCharTok{$}\NormalTok{revenue)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 228062987
\end{verbatim}

\textbf{Your Answer:}

The average revenues of all the movies in the given data is
88.846.315,00. Meanwhile the average revenue of all movies in the list
starring Bruce Willis is 228.062.987,00 which lies over the average
total mean.

\emph{step c}

\textbf{Your Answer:}

Average is only 8 observations so its easily skewed by 1 or 2
blockbusters like Armageddon. The law of large numbers states that the
sample mean converges to the true mean as the sample size grows, so we
shouldnt put too much emphasis on this number with n=8.

3 For this question, you will assume that your data set is the full
population.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Recode profits such that it is expressed in millions. What is the
  variance of the variable profits (in millions) in your data set?
  \textbf{[2 points]}
\item
  Create a new data set, called movies\_sample. Make sure that it is a
  random sample of your data set of 25 movies. What is the variance of
  profits in this random sample? How does it compare to the variance of
  profits in 2a? \textbf{[2 points]}
\item
  In a for loop, create 100 different samples of 25 movies, as in b, and
  estimate the variance within each sample. Save the variance of each
  sample in a vector called sample\_vars. So the first position of the
  vector would have the variance of the first sample, the second
  position the variance of the second sample, etc. Print the start of
  this vector. \textbf{[2 points]}
\item
  Summarize and make a histogram of sample\_vars. What is the mean,
  standard deviation and shape of its distribution? \textbf{[2 points]}
\item
  In your opinion, is a sample of 25 movies sufficient to get a reliable
  estimate of the population variance of profits, using the sample
  variance? Explain? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies5}\SpecialCharTok{$}\NormalTok{profits }\OtherTok{\textless{}{-}}\NormalTok{ movies5}\SpecialCharTok{$}\NormalTok{revenue }\SpecialCharTok{{-}}\NormalTok{ movies5}\SpecialCharTok{$}\NormalTok{budget}

\NormalTok{movies5}\SpecialCharTok{$}\NormalTok{profits }\OtherTok{\textless{}{-}}\NormalTok{ movies5}\SpecialCharTok{$}\NormalTok{profits }\SpecialCharTok{/} \DecValTok{1000000}

\FunctionTok{mean}\NormalTok{((movies5}\SpecialCharTok{$}\NormalTok{profits }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{profits))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 17802.62
\end{verbatim}

\textbf{Your Answer:}

The variance of profits is 17,802.62.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{movies\_sample }\OtherTok{\textless{}{-}}\NormalTok{ movies5[}\FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(movies5), }\DecValTok{25}\NormalTok{), ]}
\FunctionTok{var}\NormalTok{(movies\_sample}\SpecialCharTok{$}\NormalTok{profits, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 20712.43
\end{verbatim}

\textbf{Your Answer:}

The variance of profits in the random sample is 20,712.43. This is
higher than the variance of profits in the full dataset, which is
17,802.62. This difference is because the sample only contains 25
randomly selected movies.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies5}\SpecialCharTok{$}\NormalTok{profits }\OtherTok{\textless{}{-}}\NormalTok{ (movies5}\SpecialCharTok{$}\NormalTok{revenue }\SpecialCharTok{{-}}\NormalTok{ movies5}\SpecialCharTok{$}\NormalTok{budget) }\SpecialCharTok{/} \DecValTok{1000000}

\NormalTok{sample\_vars }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{()}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{100}\NormalTok{) \{}
\NormalTok{  movies\_sample }\OtherTok{\textless{}{-}}\NormalTok{ movies5[}\FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(movies5), }\DecValTok{25}\NormalTok{), ]}
\NormalTok{  sample\_vars[i] }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(movies\_sample}\SpecialCharTok{$}\NormalTok{profits)}
\NormalTok{\}}
\FunctionTok{head}\NormalTok{(sample\_vars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  8899.277 16467.070 13165.586  6328.324  5646.612  8375.528
\end{verbatim}

\textbf{Your Answer:}

The variances range from about 1,800 to 75,000 across the 100 samples
because each sample of 25 picks up a different mix of high and low
profit movies.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(sample\_vars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1841    5522   11680   17063   23000   75455
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(sample\_vars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15434.27
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(sample\_vars,}
     \AttributeTok{main =} \StringTok{"Histogram of Sample Variances"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"Sample Variance"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment-2-Submission-1_files/Assignment-2-Submission-1_files/figure-latex/unnamed-chunk-14-1.pdf}}

\textbf{Your Answer:} The 100 sample variances have a mean of about
17000 and a sd of about 15400. The distribution is right skewed and the
mean is higher than the median because some samples have higher profit
movies which cause larger variance.

\emph{step e}

\textbf{Your Answer:} Not reliable because the sd of the sample
variances is nearly as large as the mean so a sample of 25 can give a
very different results from the actual population variance.

\section{Week 3}\label{week-3}

For the next part of the assignment, assume that the movies in your data
frame are a random sample of a larger population of movies.

1

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create a new data set that only includes movies that are of the genre
  ``Thriller''. For these thriller movies, give a 99 percent confidence
  interval for the variable \emph{runtime}. Interpret the result.
  \textbf{[2 points]}
\item
  Now, assume that the variance of \emph{runtime} amongst thriller
  movies in your data is exactly the same as the variance of
  \emph{runtime} in the population. Under this assumption, give a 99
  percent confidence interval for the variable \emph{runtime} among
  thriller movies. Interpret the result. Is you confidence interval
  wider or less wide than the one you found under question 1a? Why is
  that the case? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{thrillers }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(movies5, genre }\SpecialCharTok{==} \StringTok{"Thriller"}\NormalTok{)}
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(thrillers)}
\NormalTok{xbar }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(thrillers}\SpecialCharTok{$}\NormalTok{runtime)}
\NormalTok{s }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(thrillers}\SpecialCharTok{$}\NormalTok{runtime)}
\NormalTok{t\_crit }\OtherTok{\textless{}{-}} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.995}\NormalTok{, }\AttributeTok{df =}\NormalTok{ n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)}
\FunctionTok{c}\NormalTok{(xbar }\SpecialCharTok{{-}}\NormalTok{ t\_crit }\SpecialCharTok{*}\NormalTok{ s }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n), xbar }\SpecialCharTok{+}\NormalTok{ t\_crit }\SpecialCharTok{*}\NormalTok{ s }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 102.6930 109.7007
\end{verbatim}

\textbf{Your Answer:}

The 99\% confidence interval for the mean runtime of thriller movies is
{[}102.69, 109.70{]} minutes. This means we are 99\% confident that the
real average runtime of all thriller movies in the population lies
between roughly 102.7 and 109.7 minutes.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pop\_sd }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{runtime, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{z\_crit }\OtherTok{\textless{}{-}} \FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.995}\NormalTok{)}
\FunctionTok{c}\NormalTok{(xbar }\SpecialCharTok{{-}}\NormalTok{ z\_crit }\SpecialCharTok{*}\NormalTok{ pop\_sd }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n), xbar }\SpecialCharTok{+}\NormalTok{ z\_crit }\SpecialCharTok{*}\NormalTok{ pop\_sd }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 101.6449 110.7488
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15.09759
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pop\_sd}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 19.91493
\end{verbatim}

\textbf{Your Answer:}

The 99\% CI is {[}101.64, 110.75{]}, which is wider than in 1a. This is
because the sd of runtime for all movies (19.91) is bigger than the sd
of only the thrillers (15.10), and that matters more than the smaller z
critical value.

2

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Using an appropriate five-step procedure, set up a test for the null
  hypothesis that the variance of runtime equals \(500\). Clearly state
  your null hypothesis, alternative hypothesis your test statistic, your
  critical value, and your conclusion. \textbf{[2 points]}
\item
  For the validity of your test in 2a, what assumption about the
  distribution of revenue needs to hold? Make an appropriate plot to
  test this assumption. What do you conclude? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{runtime }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{runtime)}

\NormalTok{n  }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(runtime)}
\NormalTok{s2 }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(runtime)          }\CommentTok{\# sample variance}


\NormalTok{chi2 }\OtherTok{\textless{}{-}}\NormalTok{ (n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ s2 }\SpecialCharTok{/} \DecValTok{500}

\CommentTok{\# Critical values (two{-}sided, alpha = 0.05)}
\NormalTok{lower\_crit }\OtherTok{\textless{}{-}} \FunctionTok{qchisq}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\AttributeTok{df =}\NormalTok{ n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)}
\NormalTok{upper\_crit }\OtherTok{\textless{}{-}} \FunctionTok{qchisq}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\AttributeTok{df =}\NormalTok{ n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)}

\NormalTok{n}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 909
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 396.6046
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{chi2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 720.234
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lower\_crit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 826.3872
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{upper\_crit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 993.4009
\end{verbatim}

\textbf{Your Answer:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Hypotheses H(0): VAR = 500 H(1): VAR ≠ 500
\item
  Test statistic Chi² = (n − 1) · s² / SD(0)², which follows a
  chi-square distribution with n − 1 degrees of freedom under H(0).
\item
  Significance level and critical values alpha = 0.05, two-sided test
  with 908 degrees of freedom. The critical values are 826.39 and
  993.40. We reject H(0) if Chi² \textless{} 826.39 or Chi²
  \textgreater{} 993.40.
\item
  Calculation n = 909, s² = 396.60 Chi² = 908 × 396.60 / 500 = 720.23
\item
  Conclusion Since 720.23 \textless{} 826.39, the test statistic falls
  in the rejection region, so we reject H(0). At the 5\% significance
  level, there is enough evidence that the variance of runtime is not
  equal to 500. The sample variance is lower, which suggests the true
  variance is smaller than 500.
\end{enumerate}

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{))}

\FunctionTok{hist}\NormalTok{(runtime, }\AttributeTok{breaks =} \DecValTok{40}\NormalTok{, }\AttributeTok{main =} \StringTok{"Histogram of runtime"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"Runtime (minutes)"}\NormalTok{)}

\FunctionTok{qqnorm}\NormalTok{(runtime, }\AttributeTok{main =} \StringTok{"Normal QQ plot of runtime"}\NormalTok{)}
\FunctionTok{qqline}\NormalTok{(runtime, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment-2-Submission-1_files/Assignment-2-Submission-1_files/figure-latex/unnamed-chunk-19-1.pdf}}

\textbf{Your Answer:}

The chi-square test for the variance is only valid if runtime is
normally distributed. To check this, we made a histogram and a normal QQ
plot of runtime.

The histogram is roughly bell-shaped in the middle, but it is skewed to
the right, with a longer tail of very long movies. There are also a few
movies with a runtime of 0, which are probably missing values. In the QQ
plot, the points follow the line in the middle but move away from it at
both ends so long movies lie above the line and the 0-minute movies lie
far below it.

We conclude that runtime is not normally distributed, so the assumption
behind the test in 2a does not hold.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  There is an argument going on in the movie studio. \emph{Bob} claims
  that they should make higher-quality movies, as this will bring in
  more profits. \emph{Chantal} disagrees. She tells Bob that mediocre
  movies bring in the most profits. You are asked to advise on who is
  right.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create a new variable called vote\_average\_rounded. Make sure this
  variable is the same as vote\_average, but without any decimals (i.e.,
  a 6.3 becomes a 6, a 8.7 an 8, etc.). Display a histogram of
  vote\_average\_rounded. \textbf{[2 points]}
\item
  Create a scatter plot with vote\_average\_rounded on the x axis and
  the mean of profits within each category of vote\_average\_rounded on
  the y-axis. Make sure it has an appropriate title, and appropriate
  titles and labels for the x- and y-axis. At which rating of movies are
  profits the highest? \textbf{[3 points]}
\item
  Recreate the scatter plot with year on the x axis and mean\_profits on
  the y-axis, but now add bars around each point, indicating the 95\%
  confidence interval. \textbf{[3 points]}
\item
  Write an advice to settle the argument between Bob and Chantal.
  \textbf{[4 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movies5}\SpecialCharTok{$}\NormalTok{vote\_average\_rounded }\OtherTok{\textless{}{-}} \FunctionTok{floor}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{vote\_average)}

\FunctionTok{hist}\NormalTok{(movies5}\SpecialCharTok{$}\NormalTok{vote\_average\_rounded,}
     \AttributeTok{main =} \StringTok{"Distribution of Movie Ratings"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"Movie Rating"}\NormalTok{,}
     \AttributeTok{ylab =} \StringTok{"Frequency"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment-2-Submission-1_files/Assignment-2-Submission-1_files/figure-latex/unnamed-chunk-20-1.pdf}}

\textbf{Your Answer:}

Most movies have a rating of 5, 6 or 7, and 6 is the most common rating.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mean\_profits }\OtherTok{\textless{}{-}} \FunctionTok{aggregate}\NormalTok{(profits }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vote\_average\_rounded,}
                          \AttributeTok{data =}\NormalTok{ movies5,}
                          \AttributeTok{FUN =}\NormalTok{ mean,}
                          \AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}

\FunctionTok{plot}\NormalTok{(mean\_profits}\SpecialCharTok{$}\NormalTok{vote\_average\_rounded,}
\NormalTok{     mean\_profits}\SpecialCharTok{$}\NormalTok{profits,}
     \AttributeTok{main =} \StringTok{"Average Profits by Movie Rating"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"Movie Rating"}\NormalTok{,}
     \AttributeTok{ylab =} \StringTok{"Mean Profits"}\NormalTok{,}
     \AttributeTok{pch =} \DecValTok{19}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment-2-Submission-1_files/Assignment-2-Submission-1_files/figure-latex/unnamed-chunk-21-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mean\_profits[}\FunctionTok{which.max}\NormalTok{(mean\_profits}\SpecialCharTok{$}\NormalTok{profits), ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   vote_average_rounded  profits
## 7                    7 107.5851
\end{verbatim}

\textbf{Your Answer:}

Movies with a rating of 7 have the highest average profits, about 107.59
million.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}

\NormalTok{year\_profits }\OtherTok{\textless{}{-}}\NormalTok{ movies5 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(release\_year) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{mean\_profits =} \FunctionTok{mean}\NormalTok{(profits, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{sd\_profits =} \FunctionTok{sd}\NormalTok{(profits, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{n =} \FunctionTok{sum}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(profits))}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{se =}\NormalTok{ sd\_profits }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n),}
    \AttributeTok{lower =}\NormalTok{ mean\_profits }\SpecialCharTok{{-}} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\AttributeTok{df =}\NormalTok{ n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ se,}
    \AttributeTok{upper =}\NormalTok{ mean\_profits }\SpecialCharTok{+} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\AttributeTok{df =}\NormalTok{ n }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ se}
\NormalTok{  )}

\FunctionTok{plot}\NormalTok{(year\_profits}\SpecialCharTok{$}\NormalTok{release\_year,}
\NormalTok{     year\_profits}\SpecialCharTok{$}\NormalTok{mean\_profits,}
     \AttributeTok{main =} \StringTok{"Mean Profits by Year (95\% CI)"}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"Year"}\NormalTok{,}
     \AttributeTok{ylab =} \StringTok{"Mean Profits (millions)"}\NormalTok{,}
        \AttributeTok{pch =} \DecValTok{19}\NormalTok{,}
   \AttributeTok{ylim =} \FunctionTok{range}\NormalTok{(year\_profits}\SpecialCharTok{$}\NormalTok{lower, year\_profits}\SpecialCharTok{$}\NormalTok{upper))}

\FunctionTok{arrows}\NormalTok{(year\_profits}\SpecialCharTok{$}\NormalTok{release\_year,}
\NormalTok{       year\_profits}\SpecialCharTok{$}\NormalTok{lower,}
\NormalTok{       year\_profits}\SpecialCharTok{$}\NormalTok{release\_year,}
\NormalTok{       year\_profits}\SpecialCharTok{$}\NormalTok{upper,}
       \AttributeTok{angle =} \DecValTok{90}\NormalTok{,}
       \AttributeTok{code =} \DecValTok{3}\NormalTok{,}
       \AttributeTok{length =} \FloatTok{0.05}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment-2-Submission-1_files/Assignment-2-Submission-1_files/figure-latex/unnamed-chunk-22-1.pdf}}

\textbf{Your Answer:}

The mean profits are different every year, but the confidence intervals
are wide and are mostly similar with overlaps so there is no clear
pattern over the years.

\emph{step d}

\textbf{Your Answer:}

Chantal is not right, because movies with a rating of 5 make much less
profit (about 33 million) than movies with a rating of 7 (about 108
million). Bob is partly right, since profits go up with the rating until
7, but the few movies rated 8 or 9 do not make more. We would advise the
studio to aim for good movies, around a rating of 7.

\end{document}
